# Creating and Printing Two Random 5-Dimensional Vectors

In [1]:
import numpy as np

In [2]:
np.random.seed(42)
u = np.random.randint(-15, 16, 5)
v = np.random.randint(-15, 16, 5)

In [3]:
print("Vector u (5D):")
print(u)
print("\nVector v (5D):")
print(v)

Vector u (5D):
[-9  4 13 -1 -5]

Vector v (5D):
[-8 13  5 -9 10]


# Finding the Vector $(3\mathbf{u} - 2\mathbf{v})$

In [4]:
three_u = 3 * u
two_v = 2 * v

In [5]:
result_vector = three_u - two_v

In [6]:
print("The vectors used:")
print(f"u: {u}")
print(f"v: {v}")
print("\nResult of (3u - 2v):")
print(result_vector)

The vectors used:
u: [-9  4 13 -1 -5]
v: [-8 13  5 -9 10]

Result of (3u - 2v):
[-11 -14  29  15 -35]


# Verifying the Norm Property

In [7]:
import numpy as np

# 1. Define the 2-dimensional vector u
u = np.array([-2, -4])

# 2. Calculate the norm of u (||u||)
norm_u = np.linalg.norm(u)

# 3. Calculate 4 * ||u|| (Right-Hand Side, RHS)
rhs = 4 * norm_u

# 4. Calculate the vector 4u
vector_four_u = 4 * u

# 5. Calculate the norm of 4u (||4u||) (Left-Hand Side, LHS)
norm_four_u = np.linalg.norm(vector_four_u)
lhs = norm_four_u

In [8]:
# 6. Verify the equality
print(f"Vector u: {u}")
print(f"Vector 4u: {vector_four_u}")
print("-" * 30)

print(f"||u||: {norm_u:.4f}")
print(f"4 * ||u|| (RHS): {rhs:.4f}")
print(f"||4u|| (LHS): {lhs:.4f}")

Vector u: [-2 -4]
Vector 4u: [ -8 -16]
------------------------------
||u||: 4.4721
4 * ||u|| (RHS): 17.8885
||4u|| (LHS): 17.8885


In [9]:
# Verification check
if np.isclose(lhs, rhs):
    print("\nVerification successful: ||4u|| = 4 * ||u|| is TRUE.")
else:
    print("\nVerification failed.")


Verification successful: ||4u|| = 4 * ||u|| is TRUE.
